- hosts: all
  become: yes
  tasks:
    - name: install prerequests
      apt: name={{item}} state=present
      with_items:
      - build-essential
      - git
      - yasm
      - unzip
      - wget
      - sysstat
    
    - name: 